enable_artifact_metadata: True
enable_artifact_visualization: True
enable_step_logs: True

extra:
  tags: zenml-projects

settings:
  docker:
    required_integrations:
      - mlflow

steps:
  ingest_data:
    enable_cache: True

  prepare_data:
    enable_cache: True

  model_train:
    enable_cache: True
    experiment_tracker: mlflow_tracker

  model_eval:
    enable_cache: True
    experiment_tracker: mlflow_tracker

